[package]
name = "pixel_sprite_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
dotenv = "0.15.0"
image = "0.24.8"
oauth2 = "4.4.2"
serde = "1.0.196"
